apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- include "ghrunner-unibe.serviceAccountName" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ghrunner-unibe.serviceAccountLabels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.secretManagement.clientId }}